# [START runtime]
runtime: nodejs10
handlers:
- url: / 
  static_files: dist/icecream-parlour/index.html 
  upload: dist/icecream-parlour/index.html 
- url: / 
  static_dir: dist/icecream-parlour/
# [END runtime]

